// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: helloworld.proto
#ifndef GRPC_helloworld_2eproto__INCLUDED
#define GRPC_helloworld_2eproto__INCLUDED

#include "helloworld.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace helloworld {

class Greeter final {
 public:
  static constexpr char const* service_full_name() {
    return "helloworld.Greeter";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderInterface< ::helloworld::FrameStatus>> ProcessVideo(::grpc::ClientContext* context, const ::helloworld::ProcessRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::helloworld::FrameStatus>>(ProcessVideoRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::helloworld::FrameStatus>> AsyncProcessVideo(::grpc::ClientContext* context, const ::helloworld::ProcessRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::helloworld::FrameStatus>>(AsyncProcessVideoRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::helloworld::FrameStatus>> PrepareAsyncProcessVideo(::grpc::ClientContext* context, const ::helloworld::ProcessRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::helloworld::FrameStatus>>(PrepareAsyncProcessVideoRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void ProcessVideo(::grpc::ClientContext* context, const ::helloworld::ProcessRequest* request, ::grpc::ClientReadReactor< ::helloworld::FrameStatus>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderInterface< ::helloworld::FrameStatus>* ProcessVideoRaw(::grpc::ClientContext* context, const ::helloworld::ProcessRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::helloworld::FrameStatus>* AsyncProcessVideoRaw(::grpc::ClientContext* context, const ::helloworld::ProcessRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::helloworld::FrameStatus>* PrepareAsyncProcessVideoRaw(::grpc::ClientContext* context, const ::helloworld::ProcessRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReader< ::helloworld::FrameStatus>> ProcessVideo(::grpc::ClientContext* context, const ::helloworld::ProcessRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::helloworld::FrameStatus>>(ProcessVideoRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::helloworld::FrameStatus>> AsyncProcessVideo(::grpc::ClientContext* context, const ::helloworld::ProcessRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::helloworld::FrameStatus>>(AsyncProcessVideoRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::helloworld::FrameStatus>> PrepareAsyncProcessVideo(::grpc::ClientContext* context, const ::helloworld::ProcessRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::helloworld::FrameStatus>>(PrepareAsyncProcessVideoRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ProcessVideo(::grpc::ClientContext* context, const ::helloworld::ProcessRequest* request, ::grpc::ClientReadReactor< ::helloworld::FrameStatus>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReader< ::helloworld::FrameStatus>* ProcessVideoRaw(::grpc::ClientContext* context, const ::helloworld::ProcessRequest& request) override;
    ::grpc::ClientAsyncReader< ::helloworld::FrameStatus>* AsyncProcessVideoRaw(::grpc::ClientContext* context, const ::helloworld::ProcessRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::helloworld::FrameStatus>* PrepareAsyncProcessVideoRaw(::grpc::ClientContext* context, const ::helloworld::ProcessRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ProcessVideo_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ProcessVideo(::grpc::ServerContext* context, const ::helloworld::ProcessRequest* request, ::grpc::ServerWriter< ::helloworld::FrameStatus>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_ProcessVideo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ProcessVideo() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ProcessVideo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessVideo(::grpc::ServerContext* /*context*/, const ::helloworld::ProcessRequest* /*request*/, ::grpc::ServerWriter< ::helloworld::FrameStatus>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestProcessVideo(::grpc::ServerContext* context, ::helloworld::ProcessRequest* request, ::grpc::ServerAsyncWriter< ::helloworld::FrameStatus>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ProcessVideo<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ProcessVideo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ProcessVideo() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::helloworld::ProcessRequest, ::helloworld::FrameStatus>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::helloworld::ProcessRequest* request) { return this->ProcessVideo(context, request); }));
    }
    ~WithCallbackMethod_ProcessVideo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessVideo(::grpc::ServerContext* /*context*/, const ::helloworld::ProcessRequest* /*request*/, ::grpc::ServerWriter< ::helloworld::FrameStatus>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::helloworld::FrameStatus>* ProcessVideo(
      ::grpc::CallbackServerContext* /*context*/, const ::helloworld::ProcessRequest* /*request*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ProcessVideo<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ProcessVideo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ProcessVideo() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ProcessVideo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessVideo(::grpc::ServerContext* /*context*/, const ::helloworld::ProcessRequest* /*request*/, ::grpc::ServerWriter< ::helloworld::FrameStatus>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ProcessVideo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ProcessVideo() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ProcessVideo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessVideo(::grpc::ServerContext* /*context*/, const ::helloworld::ProcessRequest* /*request*/, ::grpc::ServerWriter< ::helloworld::FrameStatus>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestProcessVideo(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ProcessVideo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ProcessVideo() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->ProcessVideo(context, request); }));
    }
    ~WithRawCallbackMethod_ProcessVideo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessVideo(::grpc::ServerContext* /*context*/, const ::helloworld::ProcessRequest* /*request*/, ::grpc::ServerWriter< ::helloworld::FrameStatus>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* ProcessVideo(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_ProcessVideo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_ProcessVideo() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::helloworld::ProcessRequest, ::helloworld::FrameStatus>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::helloworld::ProcessRequest, ::helloworld::FrameStatus>* streamer) {
                       return this->StreamedProcessVideo(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_ProcessVideo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ProcessVideo(::grpc::ServerContext* /*context*/, const ::helloworld::ProcessRequest* /*request*/, ::grpc::ServerWriter< ::helloworld::FrameStatus>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedProcessVideo(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::helloworld::ProcessRequest,::helloworld::FrameStatus>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_ProcessVideo<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_ProcessVideo<Service > StreamedService;
};

}  // namespace helloworld


#endif  // GRPC_helloworld_2eproto__INCLUDED
